
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Account` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Account
 * 
 */
export type AccountModel = runtime.Types.Result.DefaultSelection<Prisma.$AccountPayload>

export type AggregateAccount = {
  _count: AccountCountAggregateOutputType | null
  _avg: AccountAvgAggregateOutputType | null
  _sum: AccountSumAggregateOutputType | null
  _min: AccountMinAggregateOutputType | null
  _max: AccountMaxAggregateOutputType | null
}

export type AccountAvgAggregateOutputType = {
  balance: runtime.Decimal | null
}

export type AccountSumAggregateOutputType = {
  balance: runtime.Decimal | null
}

export type AccountMinAggregateOutputType = {
  id: string | null
  tenantId: string | null
  profileId: string | null
  name: string | null
  balance: runtime.Decimal | null
  createdBy: string | null
  createdAt: Date | null
  updatedBy: string | null
  updatedAt: Date | null
  deletedBy: string | null
  deletedAt: Date | null
}

export type AccountMaxAggregateOutputType = {
  id: string | null
  tenantId: string | null
  profileId: string | null
  name: string | null
  balance: runtime.Decimal | null
  createdBy: string | null
  createdAt: Date | null
  updatedBy: string | null
  updatedAt: Date | null
  deletedBy: string | null
  deletedAt: Date | null
}

export type AccountCountAggregateOutputType = {
  id: number
  tenantId: number
  profileId: number
  name: number
  balance: number
  createdBy: number
  createdAt: number
  updatedBy: number
  updatedAt: number
  deletedBy: number
  deletedAt: number
  _all: number
}


export type AccountAvgAggregateInputType = {
  balance?: true
}

export type AccountSumAggregateInputType = {
  balance?: true
}

export type AccountMinAggregateInputType = {
  id?: true
  tenantId?: true
  profileId?: true
  name?: true
  balance?: true
  createdBy?: true
  createdAt?: true
  updatedBy?: true
  updatedAt?: true
  deletedBy?: true
  deletedAt?: true
}

export type AccountMaxAggregateInputType = {
  id?: true
  tenantId?: true
  profileId?: true
  name?: true
  balance?: true
  createdBy?: true
  createdAt?: true
  updatedBy?: true
  updatedAt?: true
  deletedBy?: true
  deletedAt?: true
}

export type AccountCountAggregateInputType = {
  id?: true
  tenantId?: true
  profileId?: true
  name?: true
  balance?: true
  createdBy?: true
  createdAt?: true
  updatedBy?: true
  updatedAt?: true
  deletedBy?: true
  deletedAt?: true
  _all?: true
}

export type AccountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Account to aggregate.
   */
  where?: Prisma.AccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accounts to fetch.
   */
  orderBy?: Prisma.AccountOrderByWithRelationInput | Prisma.AccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Accounts
  **/
  _count?: true | AccountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AccountAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AccountSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccountMaxAggregateInputType
}

export type GetAccountAggregateType<T extends AccountAggregateArgs> = {
      [P in keyof T & keyof AggregateAccount]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccount[P]>
    : Prisma.GetScalarType<T[P], AggregateAccount[P]>
}




export type AccountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountWhereInput
  orderBy?: Prisma.AccountOrderByWithAggregationInput | Prisma.AccountOrderByWithAggregationInput[]
  by: Prisma.AccountScalarFieldEnum[] | Prisma.AccountScalarFieldEnum
  having?: Prisma.AccountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccountCountAggregateInputType | true
  _avg?: AccountAvgAggregateInputType
  _sum?: AccountSumAggregateInputType
  _min?: AccountMinAggregateInputType
  _max?: AccountMaxAggregateInputType
}

export type AccountGroupByOutputType = {
  id: string
  tenantId: string
  profileId: string | null
  name: string
  balance: runtime.Decimal
  createdBy: string
  createdAt: Date
  updatedBy: string | null
  updatedAt: Date
  deletedBy: string | null
  deletedAt: Date | null
  _count: AccountCountAggregateOutputType | null
  _avg: AccountAvgAggregateOutputType | null
  _sum: AccountSumAggregateOutputType | null
  _min: AccountMinAggregateOutputType | null
  _max: AccountMaxAggregateOutputType | null
}

type GetAccountGroupByPayload<T extends AccountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccountGroupByOutputType[P]>
      }
    >
  >



export type AccountWhereInput = {
  AND?: Prisma.AccountWhereInput | Prisma.AccountWhereInput[]
  OR?: Prisma.AccountWhereInput[]
  NOT?: Prisma.AccountWhereInput | Prisma.AccountWhereInput[]
  id?: Prisma.UuidFilter<"Account"> | string
  tenantId?: Prisma.UuidFilter<"Account"> | string
  profileId?: Prisma.UuidNullableFilter<"Account"> | string | null
  name?: Prisma.StringFilter<"Account"> | string
  balance?: Prisma.DecimalFilter<"Account"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFilter<"Account"> | string
  createdAt?: Prisma.DateTimeFilter<"Account"> | Date | string
  updatedBy?: Prisma.StringNullableFilter<"Account"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"Account"> | Date | string
  deletedBy?: Prisma.StringNullableFilter<"Account"> | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"Account"> | Date | string | null
  tenant?: Prisma.XOR<Prisma.TenantScalarRelationFilter, Prisma.TenantWhereInput>
  profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null
  fromLedgerEntries?: Prisma.LedgerEntryListRelationFilter
  toLedgerEntries?: Prisma.LedgerEntryListRelationFilter
}

export type AccountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  profileId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  tenant?: Prisma.TenantOrderByWithRelationInput
  profile?: Prisma.ProfileOrderByWithRelationInput
  fromLedgerEntries?: Prisma.LedgerEntryOrderByRelationAggregateInput
  toLedgerEntries?: Prisma.LedgerEntryOrderByRelationAggregateInput
}

export type AccountWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AccountWhereInput | Prisma.AccountWhereInput[]
  OR?: Prisma.AccountWhereInput[]
  NOT?: Prisma.AccountWhereInput | Prisma.AccountWhereInput[]
  tenantId?: Prisma.UuidFilter<"Account"> | string
  profileId?: Prisma.UuidNullableFilter<"Account"> | string | null
  name?: Prisma.StringFilter<"Account"> | string
  balance?: Prisma.DecimalFilter<"Account"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFilter<"Account"> | string
  createdAt?: Prisma.DateTimeFilter<"Account"> | Date | string
  updatedBy?: Prisma.StringNullableFilter<"Account"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"Account"> | Date | string
  deletedBy?: Prisma.StringNullableFilter<"Account"> | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"Account"> | Date | string | null
  tenant?: Prisma.XOR<Prisma.TenantScalarRelationFilter, Prisma.TenantWhereInput>
  profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null
  fromLedgerEntries?: Prisma.LedgerEntryListRelationFilter
  toLedgerEntries?: Prisma.LedgerEntryListRelationFilter
}, "id">

export type AccountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  profileId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AccountCountOrderByAggregateInput
  _avg?: Prisma.AccountAvgOrderByAggregateInput
  _max?: Prisma.AccountMaxOrderByAggregateInput
  _min?: Prisma.AccountMinOrderByAggregateInput
  _sum?: Prisma.AccountSumOrderByAggregateInput
}

export type AccountScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccountScalarWhereWithAggregatesInput | Prisma.AccountScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccountScalarWhereWithAggregatesInput | Prisma.AccountScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Account"> | string
  tenantId?: Prisma.UuidWithAggregatesFilter<"Account"> | string
  profileId?: Prisma.UuidNullableWithAggregatesFilter<"Account"> | string | null
  name?: Prisma.StringWithAggregatesFilter<"Account"> | string
  balance?: Prisma.DecimalWithAggregatesFilter<"Account"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringWithAggregatesFilter<"Account"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Account"> | Date | string
  updatedBy?: Prisma.StringNullableWithAggregatesFilter<"Account"> | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Account"> | Date | string
  deletedBy?: Prisma.StringNullableWithAggregatesFilter<"Account"> | string | null
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Account"> | Date | string | null
}

export type AccountCreateInput = {
  id?: string
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
  tenant: Prisma.TenantCreateNestedOneWithoutAccountsInput
  profile?: Prisma.ProfileCreateNestedOneWithoutAccountsInput
  fromLedgerEntries?: Prisma.LedgerEntryCreateNestedManyWithoutFromAccountInput
  toLedgerEntries?: Prisma.LedgerEntryCreateNestedManyWithoutToAccountInput
}

export type AccountUncheckedCreateInput = {
  id?: string
  tenantId: string
  profileId?: string | null
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
  fromLedgerEntries?: Prisma.LedgerEntryUncheckedCreateNestedManyWithoutFromAccountInput
  toLedgerEntries?: Prisma.LedgerEntryUncheckedCreateNestedManyWithoutToAccountInput
}

export type AccountUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tenant?: Prisma.TenantUpdateOneRequiredWithoutAccountsNestedInput
  profile?: Prisma.ProfileUpdateOneWithoutAccountsNestedInput
  fromLedgerEntries?: Prisma.LedgerEntryUpdateManyWithoutFromAccountNestedInput
  toLedgerEntries?: Prisma.LedgerEntryUpdateManyWithoutToAccountNestedInput
}

export type AccountUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fromLedgerEntries?: Prisma.LedgerEntryUncheckedUpdateManyWithoutFromAccountNestedInput
  toLedgerEntries?: Prisma.LedgerEntryUncheckedUpdateManyWithoutToAccountNestedInput
}

export type AccountCreateManyInput = {
  id?: string
  tenantId: string
  profileId?: string | null
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
}

export type AccountUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AccountUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AccountListRelationFilter = {
  every?: Prisma.AccountWhereInput
  some?: Prisma.AccountWhereInput
  none?: Prisma.AccountWhereInput
}

export type AccountOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AccountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedBy?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type AccountAvgOrderByAggregateInput = {
  balance?: Prisma.SortOrder
}

export type AccountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedBy?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type AccountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedBy?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedBy?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type AccountSumOrderByAggregateInput = {
  balance?: Prisma.SortOrder
}

export type AccountNullableScalarRelationFilter = {
  is?: Prisma.AccountWhereInput | null
  isNot?: Prisma.AccountWhereInput | null
}

export type AccountCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutTenantInput, Prisma.AccountUncheckedCreateWithoutTenantInput> | Prisma.AccountCreateWithoutTenantInput[] | Prisma.AccountUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutTenantInput | Prisma.AccountCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.AccountCreateManyTenantInputEnvelope
  connect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
}

export type AccountUncheckedCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutTenantInput, Prisma.AccountUncheckedCreateWithoutTenantInput> | Prisma.AccountCreateWithoutTenantInput[] | Prisma.AccountUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutTenantInput | Prisma.AccountCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.AccountCreateManyTenantInputEnvelope
  connect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
}

export type AccountUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutTenantInput, Prisma.AccountUncheckedCreateWithoutTenantInput> | Prisma.AccountCreateWithoutTenantInput[] | Prisma.AccountUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutTenantInput | Prisma.AccountCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.AccountUpsertWithWhereUniqueWithoutTenantInput | Prisma.AccountUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.AccountCreateManyTenantInputEnvelope
  set?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  disconnect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  delete?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  connect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  update?: Prisma.AccountUpdateWithWhereUniqueWithoutTenantInput | Prisma.AccountUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.AccountUpdateManyWithWhereWithoutTenantInput | Prisma.AccountUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.AccountScalarWhereInput | Prisma.AccountScalarWhereInput[]
}

export type AccountUncheckedUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutTenantInput, Prisma.AccountUncheckedCreateWithoutTenantInput> | Prisma.AccountCreateWithoutTenantInput[] | Prisma.AccountUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutTenantInput | Prisma.AccountCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.AccountUpsertWithWhereUniqueWithoutTenantInput | Prisma.AccountUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.AccountCreateManyTenantInputEnvelope
  set?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  disconnect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  delete?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  connect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  update?: Prisma.AccountUpdateWithWhereUniqueWithoutTenantInput | Prisma.AccountUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.AccountUpdateManyWithWhereWithoutTenantInput | Prisma.AccountUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.AccountScalarWhereInput | Prisma.AccountScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type AccountCreateNestedOneWithoutFromLedgerEntriesInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutFromLedgerEntriesInput, Prisma.AccountUncheckedCreateWithoutFromLedgerEntriesInput>
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutFromLedgerEntriesInput
  connect?: Prisma.AccountWhereUniqueInput
}

export type AccountCreateNestedOneWithoutToLedgerEntriesInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutToLedgerEntriesInput, Prisma.AccountUncheckedCreateWithoutToLedgerEntriesInput>
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutToLedgerEntriesInput
  connect?: Prisma.AccountWhereUniqueInput
}

export type AccountUpdateOneWithoutFromLedgerEntriesNestedInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutFromLedgerEntriesInput, Prisma.AccountUncheckedCreateWithoutFromLedgerEntriesInput>
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutFromLedgerEntriesInput
  upsert?: Prisma.AccountUpsertWithoutFromLedgerEntriesInput
  disconnect?: Prisma.AccountWhereInput | boolean
  delete?: Prisma.AccountWhereInput | boolean
  connect?: Prisma.AccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccountUpdateToOneWithWhereWithoutFromLedgerEntriesInput, Prisma.AccountUpdateWithoutFromLedgerEntriesInput>, Prisma.AccountUncheckedUpdateWithoutFromLedgerEntriesInput>
}

export type AccountUpdateOneWithoutToLedgerEntriesNestedInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutToLedgerEntriesInput, Prisma.AccountUncheckedCreateWithoutToLedgerEntriesInput>
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutToLedgerEntriesInput
  upsert?: Prisma.AccountUpsertWithoutToLedgerEntriesInput
  disconnect?: Prisma.AccountWhereInput | boolean
  delete?: Prisma.AccountWhereInput | boolean
  connect?: Prisma.AccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccountUpdateToOneWithWhereWithoutToLedgerEntriesInput, Prisma.AccountUpdateWithoutToLedgerEntriesInput>, Prisma.AccountUncheckedUpdateWithoutToLedgerEntriesInput>
}

export type AccountCreateNestedManyWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutProfileInput, Prisma.AccountUncheckedCreateWithoutProfileInput> | Prisma.AccountCreateWithoutProfileInput[] | Prisma.AccountUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutProfileInput | Prisma.AccountCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.AccountCreateManyProfileInputEnvelope
  connect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
}

export type AccountUncheckedCreateNestedManyWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutProfileInput, Prisma.AccountUncheckedCreateWithoutProfileInput> | Prisma.AccountCreateWithoutProfileInput[] | Prisma.AccountUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutProfileInput | Prisma.AccountCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.AccountCreateManyProfileInputEnvelope
  connect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
}

export type AccountUpdateManyWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutProfileInput, Prisma.AccountUncheckedCreateWithoutProfileInput> | Prisma.AccountCreateWithoutProfileInput[] | Prisma.AccountUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutProfileInput | Prisma.AccountCreateOrConnectWithoutProfileInput[]
  upsert?: Prisma.AccountUpsertWithWhereUniqueWithoutProfileInput | Prisma.AccountUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.AccountCreateManyProfileInputEnvelope
  set?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  disconnect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  delete?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  connect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  update?: Prisma.AccountUpdateWithWhereUniqueWithoutProfileInput | Prisma.AccountUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?: Prisma.AccountUpdateManyWithWhereWithoutProfileInput | Prisma.AccountUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.AccountScalarWhereInput | Prisma.AccountScalarWhereInput[]
}

export type AccountUncheckedUpdateManyWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.AccountCreateWithoutProfileInput, Prisma.AccountUncheckedCreateWithoutProfileInput> | Prisma.AccountCreateWithoutProfileInput[] | Prisma.AccountUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.AccountCreateOrConnectWithoutProfileInput | Prisma.AccountCreateOrConnectWithoutProfileInput[]
  upsert?: Prisma.AccountUpsertWithWhereUniqueWithoutProfileInput | Prisma.AccountUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.AccountCreateManyProfileInputEnvelope
  set?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  disconnect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  delete?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  connect?: Prisma.AccountWhereUniqueInput | Prisma.AccountWhereUniqueInput[]
  update?: Prisma.AccountUpdateWithWhereUniqueWithoutProfileInput | Prisma.AccountUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?: Prisma.AccountUpdateManyWithWhereWithoutProfileInput | Prisma.AccountUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.AccountScalarWhereInput | Prisma.AccountScalarWhereInput[]
}

export type AccountCreateWithoutTenantInput = {
  id?: string
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
  profile?: Prisma.ProfileCreateNestedOneWithoutAccountsInput
  fromLedgerEntries?: Prisma.LedgerEntryCreateNestedManyWithoutFromAccountInput
  toLedgerEntries?: Prisma.LedgerEntryCreateNestedManyWithoutToAccountInput
}

export type AccountUncheckedCreateWithoutTenantInput = {
  id?: string
  profileId?: string | null
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
  fromLedgerEntries?: Prisma.LedgerEntryUncheckedCreateNestedManyWithoutFromAccountInput
  toLedgerEntries?: Prisma.LedgerEntryUncheckedCreateNestedManyWithoutToAccountInput
}

export type AccountCreateOrConnectWithoutTenantInput = {
  where: Prisma.AccountWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountCreateWithoutTenantInput, Prisma.AccountUncheckedCreateWithoutTenantInput>
}

export type AccountCreateManyTenantInputEnvelope = {
  data: Prisma.AccountCreateManyTenantInput | Prisma.AccountCreateManyTenantInput[]
  skipDuplicates?: boolean
}

export type AccountUpsertWithWhereUniqueWithoutTenantInput = {
  where: Prisma.AccountWhereUniqueInput
  update: Prisma.XOR<Prisma.AccountUpdateWithoutTenantInput, Prisma.AccountUncheckedUpdateWithoutTenantInput>
  create: Prisma.XOR<Prisma.AccountCreateWithoutTenantInput, Prisma.AccountUncheckedCreateWithoutTenantInput>
}

export type AccountUpdateWithWhereUniqueWithoutTenantInput = {
  where: Prisma.AccountWhereUniqueInput
  data: Prisma.XOR<Prisma.AccountUpdateWithoutTenantInput, Prisma.AccountUncheckedUpdateWithoutTenantInput>
}

export type AccountUpdateManyWithWhereWithoutTenantInput = {
  where: Prisma.AccountScalarWhereInput
  data: Prisma.XOR<Prisma.AccountUpdateManyMutationInput, Prisma.AccountUncheckedUpdateManyWithoutTenantInput>
}

export type AccountScalarWhereInput = {
  AND?: Prisma.AccountScalarWhereInput | Prisma.AccountScalarWhereInput[]
  OR?: Prisma.AccountScalarWhereInput[]
  NOT?: Prisma.AccountScalarWhereInput | Prisma.AccountScalarWhereInput[]
  id?: Prisma.UuidFilter<"Account"> | string
  tenantId?: Prisma.UuidFilter<"Account"> | string
  profileId?: Prisma.UuidNullableFilter<"Account"> | string | null
  name?: Prisma.StringFilter<"Account"> | string
  balance?: Prisma.DecimalFilter<"Account"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFilter<"Account"> | string
  createdAt?: Prisma.DateTimeFilter<"Account"> | Date | string
  updatedBy?: Prisma.StringNullableFilter<"Account"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"Account"> | Date | string
  deletedBy?: Prisma.StringNullableFilter<"Account"> | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"Account"> | Date | string | null
}

export type AccountCreateWithoutFromLedgerEntriesInput = {
  id?: string
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
  tenant: Prisma.TenantCreateNestedOneWithoutAccountsInput
  profile?: Prisma.ProfileCreateNestedOneWithoutAccountsInput
  toLedgerEntries?: Prisma.LedgerEntryCreateNestedManyWithoutToAccountInput
}

export type AccountUncheckedCreateWithoutFromLedgerEntriesInput = {
  id?: string
  tenantId: string
  profileId?: string | null
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
  toLedgerEntries?: Prisma.LedgerEntryUncheckedCreateNestedManyWithoutToAccountInput
}

export type AccountCreateOrConnectWithoutFromLedgerEntriesInput = {
  where: Prisma.AccountWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountCreateWithoutFromLedgerEntriesInput, Prisma.AccountUncheckedCreateWithoutFromLedgerEntriesInput>
}

export type AccountCreateWithoutToLedgerEntriesInput = {
  id?: string
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
  tenant: Prisma.TenantCreateNestedOneWithoutAccountsInput
  profile?: Prisma.ProfileCreateNestedOneWithoutAccountsInput
  fromLedgerEntries?: Prisma.LedgerEntryCreateNestedManyWithoutFromAccountInput
}

export type AccountUncheckedCreateWithoutToLedgerEntriesInput = {
  id?: string
  tenantId: string
  profileId?: string | null
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
  fromLedgerEntries?: Prisma.LedgerEntryUncheckedCreateNestedManyWithoutFromAccountInput
}

export type AccountCreateOrConnectWithoutToLedgerEntriesInput = {
  where: Prisma.AccountWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountCreateWithoutToLedgerEntriesInput, Prisma.AccountUncheckedCreateWithoutToLedgerEntriesInput>
}

export type AccountUpsertWithoutFromLedgerEntriesInput = {
  update: Prisma.XOR<Prisma.AccountUpdateWithoutFromLedgerEntriesInput, Prisma.AccountUncheckedUpdateWithoutFromLedgerEntriesInput>
  create: Prisma.XOR<Prisma.AccountCreateWithoutFromLedgerEntriesInput, Prisma.AccountUncheckedCreateWithoutFromLedgerEntriesInput>
  where?: Prisma.AccountWhereInput
}

export type AccountUpdateToOneWithWhereWithoutFromLedgerEntriesInput = {
  where?: Prisma.AccountWhereInput
  data: Prisma.XOR<Prisma.AccountUpdateWithoutFromLedgerEntriesInput, Prisma.AccountUncheckedUpdateWithoutFromLedgerEntriesInput>
}

export type AccountUpdateWithoutFromLedgerEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tenant?: Prisma.TenantUpdateOneRequiredWithoutAccountsNestedInput
  profile?: Prisma.ProfileUpdateOneWithoutAccountsNestedInput
  toLedgerEntries?: Prisma.LedgerEntryUpdateManyWithoutToAccountNestedInput
}

export type AccountUncheckedUpdateWithoutFromLedgerEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  toLedgerEntries?: Prisma.LedgerEntryUncheckedUpdateManyWithoutToAccountNestedInput
}

export type AccountUpsertWithoutToLedgerEntriesInput = {
  update: Prisma.XOR<Prisma.AccountUpdateWithoutToLedgerEntriesInput, Prisma.AccountUncheckedUpdateWithoutToLedgerEntriesInput>
  create: Prisma.XOR<Prisma.AccountCreateWithoutToLedgerEntriesInput, Prisma.AccountUncheckedCreateWithoutToLedgerEntriesInput>
  where?: Prisma.AccountWhereInput
}

export type AccountUpdateToOneWithWhereWithoutToLedgerEntriesInput = {
  where?: Prisma.AccountWhereInput
  data: Prisma.XOR<Prisma.AccountUpdateWithoutToLedgerEntriesInput, Prisma.AccountUncheckedUpdateWithoutToLedgerEntriesInput>
}

export type AccountUpdateWithoutToLedgerEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tenant?: Prisma.TenantUpdateOneRequiredWithoutAccountsNestedInput
  profile?: Prisma.ProfileUpdateOneWithoutAccountsNestedInput
  fromLedgerEntries?: Prisma.LedgerEntryUpdateManyWithoutFromAccountNestedInput
}

export type AccountUncheckedUpdateWithoutToLedgerEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fromLedgerEntries?: Prisma.LedgerEntryUncheckedUpdateManyWithoutFromAccountNestedInput
}

export type AccountCreateWithoutProfileInput = {
  id?: string
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
  tenant: Prisma.TenantCreateNestedOneWithoutAccountsInput
  fromLedgerEntries?: Prisma.LedgerEntryCreateNestedManyWithoutFromAccountInput
  toLedgerEntries?: Prisma.LedgerEntryCreateNestedManyWithoutToAccountInput
}

export type AccountUncheckedCreateWithoutProfileInput = {
  id?: string
  tenantId: string
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
  fromLedgerEntries?: Prisma.LedgerEntryUncheckedCreateNestedManyWithoutFromAccountInput
  toLedgerEntries?: Prisma.LedgerEntryUncheckedCreateNestedManyWithoutToAccountInput
}

export type AccountCreateOrConnectWithoutProfileInput = {
  where: Prisma.AccountWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountCreateWithoutProfileInput, Prisma.AccountUncheckedCreateWithoutProfileInput>
}

export type AccountCreateManyProfileInputEnvelope = {
  data: Prisma.AccountCreateManyProfileInput | Prisma.AccountCreateManyProfileInput[]
  skipDuplicates?: boolean
}

export type AccountUpsertWithWhereUniqueWithoutProfileInput = {
  where: Prisma.AccountWhereUniqueInput
  update: Prisma.XOR<Prisma.AccountUpdateWithoutProfileInput, Prisma.AccountUncheckedUpdateWithoutProfileInput>
  create: Prisma.XOR<Prisma.AccountCreateWithoutProfileInput, Prisma.AccountUncheckedCreateWithoutProfileInput>
}

export type AccountUpdateWithWhereUniqueWithoutProfileInput = {
  where: Prisma.AccountWhereUniqueInput
  data: Prisma.XOR<Prisma.AccountUpdateWithoutProfileInput, Prisma.AccountUncheckedUpdateWithoutProfileInput>
}

export type AccountUpdateManyWithWhereWithoutProfileInput = {
  where: Prisma.AccountScalarWhereInput
  data: Prisma.XOR<Prisma.AccountUpdateManyMutationInput, Prisma.AccountUncheckedUpdateManyWithoutProfileInput>
}

export type AccountCreateManyTenantInput = {
  id?: string
  profileId?: string | null
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
}

export type AccountUpdateWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  profile?: Prisma.ProfileUpdateOneWithoutAccountsNestedInput
  fromLedgerEntries?: Prisma.LedgerEntryUpdateManyWithoutFromAccountNestedInput
  toLedgerEntries?: Prisma.LedgerEntryUpdateManyWithoutToAccountNestedInput
}

export type AccountUncheckedUpdateWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fromLedgerEntries?: Prisma.LedgerEntryUncheckedUpdateManyWithoutFromAccountNestedInput
  toLedgerEntries?: Prisma.LedgerEntryUncheckedUpdateManyWithoutToAccountNestedInput
}

export type AccountUncheckedUpdateManyWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AccountCreateManyProfileInput = {
  id?: string
  tenantId: string
  name: string
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy: string
  createdAt?: Date | string
  updatedBy?: string | null
  updatedAt?: Date | string
  deletedBy?: string | null
  deletedAt?: Date | string | null
}

export type AccountUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tenant?: Prisma.TenantUpdateOneRequiredWithoutAccountsNestedInput
  fromLedgerEntries?: Prisma.LedgerEntryUpdateManyWithoutFromAccountNestedInput
  toLedgerEntries?: Prisma.LedgerEntryUpdateManyWithoutToAccountNestedInput
}

export type AccountUncheckedUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fromLedgerEntries?: Prisma.LedgerEntryUncheckedUpdateManyWithoutFromAccountNestedInput
  toLedgerEntries?: Prisma.LedgerEntryUncheckedUpdateManyWithoutToAccountNestedInput
}

export type AccountUncheckedUpdateManyWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type AccountCountOutputType
 */

export type AccountCountOutputType = {
  fromLedgerEntries: number
  toLedgerEntries: number
}

export type AccountCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fromLedgerEntries?: boolean | AccountCountOutputTypeCountFromLedgerEntriesArgs
  toLedgerEntries?: boolean | AccountCountOutputTypeCountToLedgerEntriesArgs
}

/**
 * AccountCountOutputType without action
 */
export type AccountCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountCountOutputType
   */
  select?: Prisma.AccountCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AccountCountOutputType without action
 */
export type AccountCountOutputTypeCountFromLedgerEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LedgerEntryWhereInput
}

/**
 * AccountCountOutputType without action
 */
export type AccountCountOutputTypeCountToLedgerEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LedgerEntryWhereInput
}


export type AccountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenantId?: boolean
  profileId?: boolean
  name?: boolean
  balance?: boolean
  createdBy?: boolean
  createdAt?: boolean
  updatedBy?: boolean
  updatedAt?: boolean
  deletedBy?: boolean
  deletedAt?: boolean
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.Account$profileArgs<ExtArgs>
  fromLedgerEntries?: boolean | Prisma.Account$fromLedgerEntriesArgs<ExtArgs>
  toLedgerEntries?: boolean | Prisma.Account$toLedgerEntriesArgs<ExtArgs>
  _count?: boolean | Prisma.AccountCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["account"]>

export type AccountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenantId?: boolean
  profileId?: boolean
  name?: boolean
  balance?: boolean
  createdBy?: boolean
  createdAt?: boolean
  updatedBy?: boolean
  updatedAt?: boolean
  deletedBy?: boolean
  deletedAt?: boolean
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.Account$profileArgs<ExtArgs>
}, ExtArgs["result"]["account"]>

export type AccountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenantId?: boolean
  profileId?: boolean
  name?: boolean
  balance?: boolean
  createdBy?: boolean
  createdAt?: boolean
  updatedBy?: boolean
  updatedAt?: boolean
  deletedBy?: boolean
  deletedAt?: boolean
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.Account$profileArgs<ExtArgs>
}, ExtArgs["result"]["account"]>

export type AccountSelectScalar = {
  id?: boolean
  tenantId?: boolean
  profileId?: boolean
  name?: boolean
  balance?: boolean
  createdBy?: boolean
  createdAt?: boolean
  updatedBy?: boolean
  updatedAt?: boolean
  deletedBy?: boolean
  deletedAt?: boolean
}

export type AccountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tenantId" | "profileId" | "name" | "balance" | "createdBy" | "createdAt" | "updatedBy" | "updatedAt" | "deletedBy" | "deletedAt", ExtArgs["result"]["account"]>
export type AccountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.Account$profileArgs<ExtArgs>
  fromLedgerEntries?: boolean | Prisma.Account$fromLedgerEntriesArgs<ExtArgs>
  toLedgerEntries?: boolean | Prisma.Account$toLedgerEntriesArgs<ExtArgs>
  _count?: boolean | Prisma.AccountCountOutputTypeDefaultArgs<ExtArgs>
}
export type AccountIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.Account$profileArgs<ExtArgs>
}
export type AccountIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.Account$profileArgs<ExtArgs>
}

export type $AccountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Account"
  objects: {
    tenant: Prisma.$TenantPayload<ExtArgs>
    profile: Prisma.$ProfilePayload<ExtArgs> | null
    fromLedgerEntries: Prisma.$LedgerEntryPayload<ExtArgs>[]
    toLedgerEntries: Prisma.$LedgerEntryPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tenantId: string
    profileId: string | null
    name: string
    balance: runtime.Decimal
    createdBy: string
    createdAt: Date
    updatedBy: string | null
    updatedAt: Date
    deletedBy: string | null
    deletedAt: Date | null
  }, ExtArgs["result"]["account"]>
  composites: {}
}

export type AccountGetPayload<S extends boolean | null | undefined | AccountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccountPayload, S>

export type AccountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccountCountAggregateInputType | true
  }

export interface AccountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Account'], meta: { name: 'Account' } }
  /**
   * Find zero or one Account that matches the filter.
   * @param {AccountFindUniqueArgs} args - Arguments to find a Account
   * @example
   * // Get one Account
   * const account = await prisma.account.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccountFindUniqueArgs>(args: Prisma.SelectSubset<T, AccountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Account that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccountFindUniqueOrThrowArgs} args - Arguments to find a Account
   * @example
   * // Get one Account
   * const account = await prisma.account.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Account that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountFindFirstArgs} args - Arguments to find a Account
   * @example
   * // Get one Account
   * const account = await prisma.account.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccountFindFirstArgs>(args?: Prisma.SelectSubset<T, AccountFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Account that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountFindFirstOrThrowArgs} args - Arguments to find a Account
   * @example
   * // Get one Account
   * const account = await prisma.account.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Accounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Accounts
   * const accounts = await prisma.account.findMany()
   * 
   * // Get first 10 Accounts
   * const accounts = await prisma.account.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accountWithIdOnly = await prisma.account.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccountFindManyArgs>(args?: Prisma.SelectSubset<T, AccountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Account.
   * @param {AccountCreateArgs} args - Arguments to create a Account.
   * @example
   * // Create one Account
   * const Account = await prisma.account.create({
   *   data: {
   *     // ... data to create a Account
   *   }
   * })
   * 
   */
  create<T extends AccountCreateArgs>(args: Prisma.SelectSubset<T, AccountCreateArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Accounts.
   * @param {AccountCreateManyArgs} args - Arguments to create many Accounts.
   * @example
   * // Create many Accounts
   * const account = await prisma.account.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccountCreateManyArgs>(args?: Prisma.SelectSubset<T, AccountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Accounts and returns the data saved in the database.
   * @param {AccountCreateManyAndReturnArgs} args - Arguments to create many Accounts.
   * @example
   * // Create many Accounts
   * const account = await prisma.account.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Accounts and only return the `id`
   * const accountWithIdOnly = await prisma.account.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Account.
   * @param {AccountDeleteArgs} args - Arguments to delete one Account.
   * @example
   * // Delete one Account
   * const Account = await prisma.account.delete({
   *   where: {
   *     // ... filter to delete one Account
   *   }
   * })
   * 
   */
  delete<T extends AccountDeleteArgs>(args: Prisma.SelectSubset<T, AccountDeleteArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Account.
   * @param {AccountUpdateArgs} args - Arguments to update one Account.
   * @example
   * // Update one Account
   * const account = await prisma.account.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccountUpdateArgs>(args: Prisma.SelectSubset<T, AccountUpdateArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Accounts.
   * @param {AccountDeleteManyArgs} args - Arguments to filter Accounts to delete.
   * @example
   * // Delete a few Accounts
   * const { count } = await prisma.account.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccountDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Accounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Accounts
   * const account = await prisma.account.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccountUpdateManyArgs>(args: Prisma.SelectSubset<T, AccountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Accounts and returns the data updated in the database.
   * @param {AccountUpdateManyAndReturnArgs} args - Arguments to update many Accounts.
   * @example
   * // Update many Accounts
   * const account = await prisma.account.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Accounts and only return the `id`
   * const accountWithIdOnly = await prisma.account.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Account.
   * @param {AccountUpsertArgs} args - Arguments to update or create a Account.
   * @example
   * // Update or create a Account
   * const account = await prisma.account.upsert({
   *   create: {
   *     // ... data to create a Account
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Account we want to update
   *   }
   * })
   */
  upsert<T extends AccountUpsertArgs>(args: Prisma.SelectSubset<T, AccountUpsertArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Accounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountCountArgs} args - Arguments to filter Accounts to count.
   * @example
   * // Count the number of Accounts
   * const count = await prisma.account.count({
   *   where: {
   *     // ... the filter for the Accounts we want to count
   *   }
   * })
  **/
  count<T extends AccountCountArgs>(
    args?: Prisma.Subset<T, AccountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Account.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccountAggregateArgs>(args: Prisma.Subset<T, AccountAggregateArgs>): Prisma.PrismaPromise<GetAccountAggregateType<T>>

  /**
   * Group by Account.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccountGroupByArgs['orderBy'] }
      : { orderBy?: AccountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Account model
 */
readonly fields: AccountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Account.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tenant<T extends Prisma.TenantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TenantDefaultArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  profile<T extends Prisma.Account$profileArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Account$profileArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  fromLedgerEntries<T extends Prisma.Account$fromLedgerEntriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Account$fromLedgerEntriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LedgerEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  toLedgerEntries<T extends Prisma.Account$toLedgerEntriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Account$toLedgerEntriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LedgerEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Account model
 */
export interface AccountFieldRefs {
  readonly id: Prisma.FieldRef<"Account", 'String'>
  readonly tenantId: Prisma.FieldRef<"Account", 'String'>
  readonly profileId: Prisma.FieldRef<"Account", 'String'>
  readonly name: Prisma.FieldRef<"Account", 'String'>
  readonly balance: Prisma.FieldRef<"Account", 'Decimal'>
  readonly createdBy: Prisma.FieldRef<"Account", 'String'>
  readonly createdAt: Prisma.FieldRef<"Account", 'DateTime'>
  readonly updatedBy: Prisma.FieldRef<"Account", 'String'>
  readonly updatedAt: Prisma.FieldRef<"Account", 'DateTime'>
  readonly deletedBy: Prisma.FieldRef<"Account", 'String'>
  readonly deletedAt: Prisma.FieldRef<"Account", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Account findUnique
 */
export type AccountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  /**
   * Filter, which Account to fetch.
   */
  where: Prisma.AccountWhereUniqueInput
}

/**
 * Account findUniqueOrThrow
 */
export type AccountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  /**
   * Filter, which Account to fetch.
   */
  where: Prisma.AccountWhereUniqueInput
}

/**
 * Account findFirst
 */
export type AccountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  /**
   * Filter, which Account to fetch.
   */
  where?: Prisma.AccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accounts to fetch.
   */
  orderBy?: Prisma.AccountOrderByWithRelationInput | Prisma.AccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Accounts.
   */
  cursor?: Prisma.AccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Accounts.
   */
  distinct?: Prisma.AccountScalarFieldEnum | Prisma.AccountScalarFieldEnum[]
}

/**
 * Account findFirstOrThrow
 */
export type AccountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  /**
   * Filter, which Account to fetch.
   */
  where?: Prisma.AccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accounts to fetch.
   */
  orderBy?: Prisma.AccountOrderByWithRelationInput | Prisma.AccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Accounts.
   */
  cursor?: Prisma.AccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Accounts.
   */
  distinct?: Prisma.AccountScalarFieldEnum | Prisma.AccountScalarFieldEnum[]
}

/**
 * Account findMany
 */
export type AccountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  /**
   * Filter, which Accounts to fetch.
   */
  where?: Prisma.AccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accounts to fetch.
   */
  orderBy?: Prisma.AccountOrderByWithRelationInput | Prisma.AccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Accounts.
   */
  cursor?: Prisma.AccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accounts.
   */
  skip?: number
  distinct?: Prisma.AccountScalarFieldEnum | Prisma.AccountScalarFieldEnum[]
}

/**
 * Account create
 */
export type AccountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  /**
   * The data needed to create a Account.
   */
  data: Prisma.XOR<Prisma.AccountCreateInput, Prisma.AccountUncheckedCreateInput>
}

/**
 * Account createMany
 */
export type AccountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Accounts.
   */
  data: Prisma.AccountCreateManyInput | Prisma.AccountCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Account createManyAndReturn
 */
export type AccountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * The data used to create many Accounts.
   */
  data: Prisma.AccountCreateManyInput | Prisma.AccountCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Account update
 */
export type AccountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  /**
   * The data needed to update a Account.
   */
  data: Prisma.XOR<Prisma.AccountUpdateInput, Prisma.AccountUncheckedUpdateInput>
  /**
   * Choose, which Account to update.
   */
  where: Prisma.AccountWhereUniqueInput
}

/**
 * Account updateMany
 */
export type AccountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Accounts.
   */
  data: Prisma.XOR<Prisma.AccountUpdateManyMutationInput, Prisma.AccountUncheckedUpdateManyInput>
  /**
   * Filter which Accounts to update
   */
  where?: Prisma.AccountWhereInput
  /**
   * Limit how many Accounts to update.
   */
  limit?: number
}

/**
 * Account updateManyAndReturn
 */
export type AccountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * The data used to update Accounts.
   */
  data: Prisma.XOR<Prisma.AccountUpdateManyMutationInput, Prisma.AccountUncheckedUpdateManyInput>
  /**
   * Filter which Accounts to update
   */
  where?: Prisma.AccountWhereInput
  /**
   * Limit how many Accounts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Account upsert
 */
export type AccountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  /**
   * The filter to search for the Account to update in case it exists.
   */
  where: Prisma.AccountWhereUniqueInput
  /**
   * In case the Account found by the `where` argument doesn't exist, create a new Account with this data.
   */
  create: Prisma.XOR<Prisma.AccountCreateInput, Prisma.AccountUncheckedCreateInput>
  /**
   * In case the Account was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccountUpdateInput, Prisma.AccountUncheckedUpdateInput>
}

/**
 * Account delete
 */
export type AccountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  /**
   * Filter which Account to delete.
   */
  where: Prisma.AccountWhereUniqueInput
}

/**
 * Account deleteMany
 */
export type AccountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Accounts to delete
   */
  where?: Prisma.AccountWhereInput
  /**
   * Limit how many Accounts to delete.
   */
  limit?: number
}

/**
 * Account.profile
 */
export type Account$profileArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  where?: Prisma.ProfileWhereInput
}

/**
 * Account.fromLedgerEntries
 */
export type Account$fromLedgerEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LedgerEntry
   */
  select?: Prisma.LedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LedgerEntry
   */
  omit?: Prisma.LedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LedgerEntryInclude<ExtArgs> | null
  where?: Prisma.LedgerEntryWhereInput
  orderBy?: Prisma.LedgerEntryOrderByWithRelationInput | Prisma.LedgerEntryOrderByWithRelationInput[]
  cursor?: Prisma.LedgerEntryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LedgerEntryScalarFieldEnum | Prisma.LedgerEntryScalarFieldEnum[]
}

/**
 * Account.toLedgerEntries
 */
export type Account$toLedgerEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LedgerEntry
   */
  select?: Prisma.LedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LedgerEntry
   */
  omit?: Prisma.LedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LedgerEntryInclude<ExtArgs> | null
  where?: Prisma.LedgerEntryWhereInput
  orderBy?: Prisma.LedgerEntryOrderByWithRelationInput | Prisma.LedgerEntryOrderByWithRelationInput[]
  cursor?: Prisma.LedgerEntryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LedgerEntryScalarFieldEnum | Prisma.LedgerEntryScalarFieldEnum[]
}

/**
 * Account without action
 */
export type AccountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
}
