#!/bin/bash

# Script to generate ECDSA P-256 keys for JWT signing
# These keys are used for ES256 (ECDSA using P-256 and SHA-256) algorithm

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
KEYS_DIR="$PROJECT_ROOT/keys"

echo "🔐 Generating ECDSA P-256 keys for JWT signing..."
echo ""

# Create keys directory if it doesn't exist
mkdir -p "$KEYS_DIR"

# Generate private key
echo "📝 Generating private key..."
openssl ecparam -genkey -name prime256v1 -noout -out "$KEYS_DIR/jwt-private-key.pem"

# Extract public key from private key
echo "📝 Extracting public key..."
openssl ec -in "$KEYS_DIR/jwt-private-key.pem" -pubout -out "$KEYS_DIR/jwt-public-key.pem"

# Set secure permissions
chmod 600 "$KEYS_DIR/jwt-private-key.pem"
chmod 644 "$KEYS_DIR/jwt-public-key.pem"

echo ""
echo "✅ Keys generated successfully!"
echo ""
echo "📁 Private key: $KEYS_DIR/jwt-private-key.pem"
echo "📁 Public key:  $KEYS_DIR/jwt-public-key.pem"
echo ""

# Convert keys to single-line format for .env
# Replace actual newlines with the literal string \n (backslash + n)
# This will be interpreted as newline when the .env file is read by dotenv parsers
PRIVATE_KEY_SINGLE_LINE=$(cat "$KEYS_DIR/jwt-private-key.pem" | sed ':a;N;$!ba;s/\n/\\n/g')
PUBLIC_KEY_SINGLE_LINE=$(cat "$KEYS_DIR/jwt-public-key.pem" | sed ':a;N;$!ba;s/\n/\\n/g')

# Add keys to .env file
ENV_FILE="$PROJECT_ROOT/.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "📝 Creating .env file..."
  touch "$ENV_FILE"
fi

# Check if JWT keys already exist in .env
if grep -q "^JWT_PRIVATE_KEY=" "$ENV_FILE"; then
  echo "⚠️  JWT_PRIVATE_KEY already exists in .env, updating..."
  # Remove existing JWT_PRIVATE_KEY line
  sed -i.bak '/^JWT_PRIVATE_KEY=/d' "$ENV_FILE" 2>/dev/null || sed -i '' '/^JWT_PRIVATE_KEY=/d' "$ENV_FILE" 2>/dev/null || true
  rm -f "$ENV_FILE.bak" 2>/dev/null || true
fi

if grep -q "^JWT_PUBLIC_KEY=" "$ENV_FILE"; then
  echo "⚠️  JWT_PUBLIC_KEY already exists in .env, updating..."
  # Remove existing JWT_PUBLIC_KEY line
  sed -i.bak '/^JWT_PUBLIC_KEY=/d' "$ENV_FILE" 2>/dev/null || sed -i '' '/^JWT_PUBLIC_KEY=/d' "$ENV_FILE" 2>/dev/null || true
  rm -f "$ENV_FILE.bak" 2>/dev/null || true
fi

# Function to add env variable if it doesn't exist
add_env_if_missing() {
  local var_name="$1"
  local var_value="$2"
  if ! grep -q "^${var_name}=" "$ENV_FILE"; then
    echo "${var_name}=${var_value}" >> "$ENV_FILE"
  fi
}

# Append JWT configuration to .env
echo "" >> "$ENV_FILE"
echo "# JWT Authentication Configuration (auto-generated by generate-jwt-keys.sh)" >> "$ENV_FILE"
# Use printf with %q to properly escape the value, then wrap in quotes
printf 'JWT_PRIVATE_KEY="%s"\n' "$PRIVATE_KEY_SINGLE_LINE" >> "$ENV_FILE"
printf 'JWT_PUBLIC_KEY="%s"\n' "$PUBLIC_KEY_SINGLE_LINE" >> "$ENV_FILE"

# Add other JWT-related variables if they don't exist
add_env_if_missing "JWT_ACCESS_TOKEN_EXPIRES_IN" "15m"
add_env_if_missing "JWT_REFRESH_TOKEN_EXPIRES_IN" "7d"
add_env_if_missing "AUTH_PROVIDER" "JWT"
add_env_if_missing "MASTER_USER_USERNAME" "admin"
add_env_if_missing "MASTER_USER_PASSWORD" "ChangeMe123!"

echo "✅ Keys and JWT configuration added to .env file!"
echo ""
echo "⚠️  IMPORTANT:"
echo "   1. Keep the private key secure and never commit it to version control"
echo "   2. The 'keys/' directory is already in .gitignore"
echo "   3. Make sure .env is in your .gitignore (it should be)"
echo "   4. Review the .env file and adjust JWT_ACCESS_TOKEN_EXPIRES_IN and JWT_REFRESH_TOKEN_EXPIRES_IN if needed"
echo ""

